
Swizzle<VectorBase, 0, 0> xx;
Swizzle<VectorBase, 0, 1> xy;
Swizzle<VectorBase, 0, 2> xz;
Swizzle<VectorBase, 1, 0> yx;
Swizzle<VectorBase, 1, 1> yy;
Swizzle<VectorBase, 1, 2> yz;
Swizzle<VectorBase, 2, 0> zx;
Swizzle<VectorBase, 2, 1> zy;
Swizzle<VectorBase, 2, 2> zz;

Swizzle<VectorBase, 0, 0, 0> xxx;
Swizzle<VectorBase, 0, 0, 1> xxy;
Swizzle<VectorBase, 0, 0, 2> xxz;
Swizzle<VectorBase, 0, 1, 0> xyx;
Swizzle<VectorBase, 0, 1, 1> xyy;
Swizzle<VectorBase, 0, 1, 2> xyz;
Swizzle<VectorBase, 0, 2, 0> xzx;
Swizzle<VectorBase, 0, 2, 1> xzy;
Swizzle<VectorBase, 0, 2, 2> xzz;
Swizzle<VectorBase, 1, 0, 0> yxx;
Swizzle<VectorBase, 1, 0, 1> yxy;
Swizzle<VectorBase, 1, 0, 2> yxz;
Swizzle<VectorBase, 1, 1, 0> yyx;
Swizzle<VectorBase, 1, 1, 1> yyy;
Swizzle<VectorBase, 1, 1, 2> yyz;
Swizzle<VectorBase, 1, 2, 0> yzx;
Swizzle<VectorBase, 1, 2, 1> yzy;
Swizzle<VectorBase, 1, 2, 2> yzz;
Swizzle<VectorBase, 2, 0, 0> zxx;
Swizzle<VectorBase, 2, 0, 1> zxy;
Swizzle<VectorBase, 2, 0, 2> zxz;
Swizzle<VectorBase, 2, 1, 0> zyx;
Swizzle<VectorBase, 2, 1, 1> zyy;
Swizzle<VectorBase, 2, 1, 2> zyz;
Swizzle<VectorBase, 2, 2, 0> zzx;
Swizzle<VectorBase, 2, 2, 1> zzy;
Swizzle<VectorBase, 2, 2, 2> zzz;

Swizzle<VectorBase, 0, 0, 0, 0> xxxx;
Swizzle<VectorBase, 0, 0, 0, 1> xxxy;
Swizzle<VectorBase, 0, 0, 0, 2> xxxz;
Swizzle<VectorBase, 0, 0, 1, 0> xxyx;
Swizzle<VectorBase, 0, 0, 1, 1> xxyy;
Swizzle<VectorBase, 0, 0, 1, 2> xxyz;
Swizzle<VectorBase, 0, 0, 2, 0> xxzx;
Swizzle<VectorBase, 0, 0, 2, 1> xxzy;
Swizzle<VectorBase, 0, 0, 2, 2> xxzz;
Swizzle<VectorBase, 0, 1, 0, 0> xyxx;
Swizzle<VectorBase, 0, 1, 0, 1> xyxy;
Swizzle<VectorBase, 0, 1, 0, 2> xyxz;
Swizzle<VectorBase, 0, 1, 1, 0> xyyx;
Swizzle<VectorBase, 0, 1, 1, 1> xyyy;
Swizzle<VectorBase, 0, 1, 1, 2> xyyz;
Swizzle<VectorBase, 0, 1, 2, 0> xyzx;
Swizzle<VectorBase, 0, 1, 2, 1> xyzy;
Swizzle<VectorBase, 0, 1, 2, 2> xyzz;
Swizzle<VectorBase, 0, 2, 0, 0> xzxx;
Swizzle<VectorBase, 0, 2, 0, 1> xzxy;
Swizzle<VectorBase, 0, 2, 0, 2> xzxz;
Swizzle<VectorBase, 0, 2, 1, 0> xzyx;
Swizzle<VectorBase, 0, 2, 1, 1> xzyy;
Swizzle<VectorBase, 0, 2, 1, 2> xzyz;
Swizzle<VectorBase, 0, 2, 2, 0> xzzx;
Swizzle<VectorBase, 0, 2, 2, 1> xzzy;
Swizzle<VectorBase, 0, 2, 2, 2> xzzz;
Swizzle<VectorBase, 1, 0, 0, 0> yxxx;
Swizzle<VectorBase, 1, 0, 0, 1> yxxy;
Swizzle<VectorBase, 1, 0, 0, 2> yxxz;
Swizzle<VectorBase, 1, 0, 1, 0> yxyx;
Swizzle<VectorBase, 1, 0, 1, 1> yxyy;
Swizzle<VectorBase, 1, 0, 1, 2> yxyz;
Swizzle<VectorBase, 1, 0, 2, 0> yxzx;
Swizzle<VectorBase, 1, 0, 2, 1> yxzy;
Swizzle<VectorBase, 1, 0, 2, 2> yxzz;
Swizzle<VectorBase, 1, 1, 0, 0> yyxx;
Swizzle<VectorBase, 1, 1, 0, 1> yyxy;
Swizzle<VectorBase, 1, 1, 0, 2> yyxz;
Swizzle<VectorBase, 1, 1, 1, 0> yyyx;
Swizzle<VectorBase, 1, 1, 1, 1> yyyy;
Swizzle<VectorBase, 1, 1, 1, 2> yyyz;
Swizzle<VectorBase, 1, 1, 2, 0> yyzx;
Swizzle<VectorBase, 1, 1, 2, 1> yyzy;
Swizzle<VectorBase, 1, 1, 2, 2> yyzz;
Swizzle<VectorBase, 1, 2, 0, 0> yzxx;
Swizzle<VectorBase, 1, 2, 0, 1> yzxy;
Swizzle<VectorBase, 1, 2, 0, 2> yzxz;
Swizzle<VectorBase, 1, 2, 1, 0> yzyx;
Swizzle<VectorBase, 1, 2, 1, 1> yzyy;
Swizzle<VectorBase, 1, 2, 1, 2> yzyz;
Swizzle<VectorBase, 1, 2, 2, 0> yzzx;
Swizzle<VectorBase, 1, 2, 2, 1> yzzy;
Swizzle<VectorBase, 1, 2, 2, 2> yzzz;
Swizzle<VectorBase, 2, 0, 0, 0> zxxx;
Swizzle<VectorBase, 2, 0, 0, 1> zxxy;
Swizzle<VectorBase, 2, 0, 0, 2> zxxz;
Swizzle<VectorBase, 2, 0, 1, 0> zxyx;
Swizzle<VectorBase, 2, 0, 1, 1> zxyy;
Swizzle<VectorBase, 2, 0, 1, 2> zxyz;
Swizzle<VectorBase, 2, 0, 2, 0> zxzx;
Swizzle<VectorBase, 2, 0, 2, 1> zxzy;
Swizzle<VectorBase, 2, 0, 2, 2> zxzz;
Swizzle<VectorBase, 2, 1, 0, 0> zyxx;
Swizzle<VectorBase, 2, 1, 0, 1> zyxy;
Swizzle<VectorBase, 2, 1, 0, 2> zyxz;
Swizzle<VectorBase, 2, 1, 1, 0> zyyx;
Swizzle<VectorBase, 2, 1, 1, 1> zyyy;
Swizzle<VectorBase, 2, 1, 1, 2> zyyz;
Swizzle<VectorBase, 2, 1, 2, 0> zyzx;
Swizzle<VectorBase, 2, 1, 2, 1> zyzy;
Swizzle<VectorBase, 2, 1, 2, 2> zyzz;
Swizzle<VectorBase, 2, 2, 0, 0> zzxx;
Swizzle<VectorBase, 2, 2, 0, 1> zzxy;
Swizzle<VectorBase, 2, 2, 0, 2> zzxz;
Swizzle<VectorBase, 2, 2, 1, 0> zzyx;
Swizzle<VectorBase, 2, 2, 1, 1> zzyy;
Swizzle<VectorBase, 2, 2, 1, 2> zzyz;
Swizzle<VectorBase, 2, 2, 2, 0> zzzx;
Swizzle<VectorBase, 2, 2, 2, 1> zzzy;
Swizzle<VectorBase, 2, 2, 2, 2> zzzz;

